# Generated by Django 5.0.7 on 2025-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_salesteams_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesshow',
            name='is_done_reassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesshow',
            name='is_reassigned',
            field=models.BooleanField(default=False),
        ),
    ]
