# Generated by Django 5.0.7 on 2025-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_salesshow_is_done_reassigned_salesshow_is_reassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadphonenumbers',
            name='time_zone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='time_zone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
