# Generated by Django 5.0.7 on 2025-08-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_migrate_time_zone_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='time_zone',
        ),
    ]
