# Generated by Django 5.0.7 on 2025-10-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_credits_credithistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'verbose_name_plural': 'Credits'},
        ),
        migrations.RemoveField(
            model_name='credits',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='credithistory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credithistory',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('refund', 'Refund'), ('monthly_reset', 'Monthly Reset'), ('expiration', 'Expiration')], max_length=20),
        ),
    ]
