# Generated by Django 5.0.7 on 2025-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_alter_credits_options_remove_credits_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontactnames',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcontactnames',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadcontactnames',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
