# Generated by Django 5.2.9 on 2026-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_flagscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='generated_mail_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_sheets/'),
        ),
    ]
