# Generated by Django 5.0.7 on 2025-10-02 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('primary_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('sanitized_phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='ai_agent.globalorganization')),
            ],
            options={
                'unique_together': {('organization', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GlobalContactNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_names', to='ai_agent.globalorganization')),
            ],
            options={
                'unique_together': {('organization', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GlobalPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('time_zone', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('sanitized_number', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='ai_agent.globalorganization')),
            ],
            options={
                'unique_together': {('organization', 'value')},
            },
        ),
    ]
