# Generated by Django 5.0.7 on 2025-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalcontactnames',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='globalcontactnames',
            unique_together={('organization', 'name')},
        ),
        migrations.RemoveField(
            model_name='globalorganization',
            name='sanitized_phone',
        ),
        migrations.RemoveField(
            model_name='globalorganization',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='globalphonenumbers',
            name='sanitized_number',
        ),
        migrations.RemoveField(
            model_name='globalphonenumbers',
            name='source',
        ),
        migrations.AddField(
            model_name='globalcontactnames',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalcontactnames',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalcontactnames',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
