# Generated by Django 5.0.7 on 2025-08-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globallead',
            table='global_leads',
        ),
        migrations.AlterModelTable(
            name='globalleadcontactnames',
            table='global_contact_names',
        ),
        migrations.AlterModelTable(
            name='globalleademails',
            table='global_emails',
        ),
        migrations.AlterModelTable(
            name='globalleadphonenumbers',
            table='global_phone_numbers',
        ),
    ]
