# Generated by Django 5.0.7 on 2025-10-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_rename_value_globalcontactnames_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('results', models.TextField(blank=True, null=True)),
                ('excel_sheet_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='globalcontactnames',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
