# Generated by Django 5.0.7 on 2025-08-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_alter_globallead_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globallead',
            table=None,
        ),
        migrations.AlterModelTable(
            name='globalleadcontactnames',
            table=None,
        ),
        migrations.AlterModelTable(
            name='globalleademails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='globalleadphonenumbers',
            table=None,
        ),
    ]
