# Generated by Django 5.0.7 on 2025-10-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_enrichmenttask_alter_globalcontactnames_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmenttask',
            name='excel_sheet_name',
            field=models.CharField(default='Enriched Leads', max_length=255),
        ),
    ]
