# Generated by Django 5.0.7 on 2025-10-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_alter_enrichmenttask_excel_sheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
