# Generated by Django 5.0.7 on 2025-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_auto_20251015_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
