# Generated by Django 5.0.7 on 2025-10-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0006_enrichmenttask_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
