# Generated by Django 5.0.7 on 2025-10-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0007_enrichmenttask_request_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='owner',
            field=models.CharField(default='IBH', max_length=255),
        ),
    ]
