# Generated by Django 5.0.7 on 2025-10-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0010_enrichmenttask_is_result_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='company_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enrichmenttask',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
