# Generated by Django 5.0.7 on 2025-10-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0012_enrichmenttask_results_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='chunks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrichmenttask',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
