# Generated by Django 5.0.7 on 2025-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0013_enrichmenttask_chunks_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmenttask',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
